CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(160) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL,
    addressee_user_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT friendship_distinct_users CHECK (requester_user_id <> addressee_user_id)
);

CREATE TABLE settle_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE group_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    left_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ux_group_member UNIQUE (group_id, user_id)
);

CREATE TABLE expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    paid_by_user_id BIGINT NOT NULL,
    description VARCHAR(240) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    total_minor BIGINT NOT NULL,
    expense_date DATE NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    cancelled_by_user_id BIGINT,
    cancellation_reason VARCHAR(500),
    CONSTRAINT expense_positive_total CHECK (total_minor > 0)
);

CREATE TABLE expense_split (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    owed_by_user_id BIGINT NOT NULL,
    split_type VARCHAR(40) NOT NULL,
    input_value NUMERIC(19, 6) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT expense_split_non_negative_amount CHECK (amount_minor >= 0)
);

CREATE TABLE settlement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    from_user_id BIGINT NOT NULL,
    to_user_id BIGINT NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    amount_minor BIGINT NOT NULL,
    settlement_date DATE NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    cancelled_by_user_id BIGINT,
    cancellation_reason VARCHAR(500),
    CONSTRAINT settlement_positive_amount CHECK (amount_minor > 0),
    CONSTRAINT settlement_distinct_users CHECK (from_user_id <> to_user_id)
);

CREATE TABLE ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    from_user_id BIGINT NOT NULL,
    to_user_id BIGINT NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    amount_minor BIGINT NOT NULL,
    direction VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ledger_entry_positive_amount CHECK (amount_minor > 0),
    CONSTRAINT ledger_entry_distinct_users CHECK (from_user_id <> to_user_id)
);

CREATE TABLE balance_projection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    from_user_id BIGINT NOT NULL,
    to_user_id BIGINT NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    amount_minor BIGINT NOT NULL,
    computed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT balance_projection_positive_amount CHECK (amount_minor > 0),
    CONSTRAINT balance_projection_distinct_users CHECK (from_user_id <> to_user_id),
    CONSTRAINT ux_balance_projection_pair UNIQUE (group_id, from_user_id, to_user_id)
);

CREATE TABLE activity_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT NOT NULL,
    message VARCHAR(500) NOT NULL,
    metadata TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE insight_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    request_type VARCHAR(80) NOT NULL,
    prompt TEXT NOT NULL,
    status VARCHAR(40) NOT NULL,
    result TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX ix_expense_group ON expense (group_id);
CREATE INDEX ix_expense_split_expense ON expense_split (expense_id);
CREATE INDEX ix_settlement_group ON settlement (group_id);
CREATE INDEX ix_ledger_entry_group ON ledger_entry (group_id);
CREATE INDEX ix_activity_event_group ON activity_event (group_id);
CREATE INDEX ix_insight_request_group ON insight_request (group_id);

UPDATE app_metadata
SET metadata_value = 'phase-1', updated_at = CURRENT_TIMESTAMP
WHERE name = 'schema_version';
